vcs: git

prerequisites:
  - working-copy-check
  - display-last-changes

pre-release-actions:
  changelog-update:
    format: pullRequest
    file: CHANGELOG.md
    repo: leviy/rmt-changelog-formatter
  vcs-commit: ~

version-generator: semantic

version-persister:
  vcs-tag:
    tag-prefix: 'v'

post-release-actions:
  vcs-publish:
    ask-confirmation: true
